### ISSUE TITLE
Not an issue! Arduino/ESP32 version

### ISSUE THREAD

**Issue by MaeseppTarvo** [yojoebosolo/Desktop-Weather#4]
Hey! Long time ago I came across your video that did show the project in action. I fell in love with it and really wanted it myself also, but then I realized that you used RaspberryPi instead of Arduino or ESP32 and thus the code is in Python. So I did write my own code in Arduino with hints of your code for it to work on Arduino/ESP32. Thought I would share it if someone is also interested in this awesome project and maybe you can/would like to mention it in your README? 🙂

I am making some changes and maybe will update it with pictures how I did it with ESP32 and how well it can be attached into the shell you made. Also be aware that it currently includes some unnecessary code(debug lines, comments, etc.)
My repository url: https://github.com/MaeseppTarvo/DesktopWeather

**Comment by yojoebosolo** [comment]
That's fantastic, thank you so much! 

I've added a link to the bottom of the Readme to link to your repo.
